# Generated by Django 2.1.5 on 2019-02-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetostore',
            name='measured_type',
            field=models.IntegerField(choices=[(1, 'post_time'), (2, 'make_dashboard'), (3, 'make_website_stats')], default=1),
        ),
    ]
