# Generated by Django 2.1.5 on 2019-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.IntegerField(blank=True, choices=[(1, 'basic'), (2, 'advanced')], null=True)),
            ],
        ),
    ]
