# Generated by Django 2.1.5 on 2019-02-06 13:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('type_device', models.IntegerField(choices=[(1, 'mobile'), (2, 'tablet'), (3, 'pc'), (4, 'bot'), (5, 'unknown')], default=5)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('device_family', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(max_length=255, null=True)),
                ('screen_height', models.IntegerField(null=True)),
                ('screen_width', models.IntegerField(null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('referrer_page', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
