# Generated by Django 2.1.5 on 2019-02-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('type_device', models.IntegerField(choices=[(1, 'mobile'), (2, 'tablet'), (3, 'pc'), (4, 'bot'), (5, 'unknown')], default=5)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('device_family', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('page', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_height', models.IntegerField(null=True)),
                ('screen_width', models.IntegerField(null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('referrer_page', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(help_text='The url of your website', max_length=255, unique=True)),
                ('website_name', models.CharField(blank=True, default='', help_text='The name of your website', max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('add_new_website', 'Can create new websites'), ('can_view_website', 'Can view the statistics')),
            },
        ),
        migrations.AddField(
            model_name='tracker',
            name='website',
            field=models.ForeignKey(default='pythonforthelab.com', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='tracker.Website', to_field='website_url'),
        ),
    ]
