# Generated by Django 2.1.5 on 2019-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
