# Generated by Django 2.1.5 on 2019-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190219_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
