# Generated by Django 2.1.5 on 2019-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190210_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_name',
            field=models.CharField(blank=True, default='', help_text='The name of your website', max_length=255),
        ),
    ]
