# Generated by Django 2.1.5 on 2019-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_website_website_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_url',
            field=models.CharField(help_text='The url of your website', max_length=255, unique=True),
        ),
    ]
