# Generated by Django 2.1.5 on 2019-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190225_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('dnt', models.BooleanField(default=False)),
                ('account_id', models.CharField(max_length=15)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
