# Generated by Django 2.1.5 on 2019-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rawtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtracker',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
