# Generated by Django 2.1.5 on 2019-02-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rawtracker_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtracker',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawtracker',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawtracker',
            name='website_does_not_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawtracker',
            name='wrong_account_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawtracker',
            name='wrong_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
