# Generated by Django 2.1.5 on 2019-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20190225_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
