# Generated by Django 2.1.5 on 2019-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'beginner'), (1, 'blogger'), (2, 'advanced')], default=0),
        ),
    ]
