# Generated by Django 2.1.5 on 2019-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_wesbites',
            field=models.IntegerField(default=1, help_text='maximum number of websites that can be registerd'),
        ),
    ]
