# Generated by Django 2.1.5 on 2019-02-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190225_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_geolocation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
