# Generated by Django 2.1.5 on 2019-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_can_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_selected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
